apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
  namespace: argocd
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/polyen/MLArgo.git
    targetRevision: main
    path: k8s/postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
