apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgres-postgresql
  namespace: application
  labels:
    app: mlflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgres
  template:
    metadata:
      labels:
        app: mlflow-postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: mlflow
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
